$ANSIBLE_VAULT;1.1;AES256
38386231386339376666346533356231333366616462336163353236313830343264646235343939
6564626439656566643333396234623466383633636137380a303538623732343235333430656531
37303937346237646338643032653131643466326439363230646634386263646532626165383232
3930626431666535370a623936393262323639366562383562633033323835393738366438306166
30313462613830663235326632623730383465376232633564303731376439663134653463666238
6239613761303030326264313131316438366136613061613135
